title: Bernhard Retzl
logo: /assets/img/portrait.jpg
description: Pharmacologist and bioinformatician with a strong background in GPCR research, proteomics, and RNA-seq data analysis, combining wet lab expertise with software development to advance drug discovery and protein family analysis.
theme: jekyll-theme-minimal